# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd74c3f6b326a19fc34f453bf1a21eee3ecc8ecbcd34712324ed42d47cccfa4379c2aa4d44e869719a734316b42fba32bac2fab74531ef72b6888eb4dd6cde67

test:
  secret_key_base: 6d64086e5d93da0562c432e2e2ec229099bf6327e2b8ac90898e4af18f3cdc90849e75c4791af7fbfec6b0142758fc8e7ce542c9d1f4db72457137240f7c134a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
